### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by FallenRiteMonk** [sindresorhus/atom-autoprefixer#29] opened 2016-04-15 15:05 UTC
Hy,

I just installed this plugin, created the same test.css as in the example and called the autoprefixer command in the command palette, but absolutely nothing happens.

I have atom v 1.7.1 running on opensuse tumbleweed

Thanks if anybody can help and if any further information is needed please let me know.

**Comment by sindresorhus** [comment] 2016-04-15 16:49
Duplicate of #28.

**Closed by sindresorhus** 2016-04-15 16:49 UTC
