### ISSUE TITLE
autoprefixing not including Mozilla

### ISSUE THREAD

**Issue by ldco2016** [sindresorhus/atom-autoprefixer#46] opened 2017-07-24 10:39 UTC
I installed autoprefixer on my atom IDE, but when I use it, -webkit is the only autoprefixing I get, nothing for mozilla firefox.

**Comment by sindresorhus** [comment] 2017-07-24 11:02
Duplicate of https://github.com/sindresorhus/atom-autoprefixer/issues/43

**Closed by sindresorhus** 2017-07-24 11:02 UTC
