### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by alex2102** [sindresorhus/atom-autoprefixer#28] opened 2016-03-26 10:39 UTC
I don't know what the problem is, but when I select my css and I open the command palette and type autoprefixer it just copies and pastes the exact same code beneath the first one. It doesn't add the prefix. I tried the prefix for the given one in the example. "box-sizing: border-box;"

**Comment by sindresorhus** [comment] 2016-03-26 10:39
Duplicate of https://github.com/sindresorhus/atom-autoprefixer/issues/26.

**Closed by sindresorhus** 2016-03-26 10:39 UTC
